# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   labels:
#     app.kubernetes.io/managed-by: kustomize
#     app.kubernetes.io/name: trial-custom
#     control-plane: controller-manager
#   name: controller-manager-metrics-monitor
#   namespace: system
# spec:
#   endpoints:
#   - path: /metrics
#     port: http
#     scheme: http
#   selector:
#     matchLabels:
#       control-plane: controller-manager
